# Generated by Django 5.0.1 on 2024-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Task',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
